services:
  api1: 
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    depends_on:
      - db
    volumes:
    - .:/usr/src/app
    - /usr/src/app/dist
    expose:
      - "3001"
    environment:
      - TIMEZONE=America/Sao_Paulo

  api2: 
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api2
    depends_on:
      - db
    volumes:
    - .:/usr/src/app
    - /usr/src/app/dist
    expose:
      - "3001"
    environment:
      - TIMEZONE=America/Sao_Paulo

  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "${NGINX_PORT:-80}:80"
  

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}

networks:
  default:
    driver: bridge
