CREATE TABLE IF NOT EXISTS gallery_item (
  id VARCHAR PRIMARY KEY,
  title VARCHAR NOT NULL,
  image_url TEXT NOT NULL,
  description TEXT DEFAULT '',
  status VARCHAR NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
