CREATE TABLE IF NOT EXISTS peca_item (
  id VARCHAR PRIMARY KEY,
  category VARCHAR NOT NULL,
  name VARCHAR NOT NULL,
  material VARCHAR NOT NULL,
  price NUMERIC(10,2) NOT NULL,
  status VARCHAR NOT NULL,
  color VARCHAR,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
